version: '3.8'

services:
  api-participadf:
    image: participadf-api
    container_name: participadf-container
    build:
      context: .
      dockerfile: SolucaoParticipaDF.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped